project_id = "reisbxeeozmvfdzruvui"

[functions.research-topic]
verify_jwt = false

[functions.generate-titles]
verify_jwt = false

[functions.generate-outline]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.generate-voice]
verify_jwt = false

[functions.generate-slides]
verify_jwt = false

[functions.search-stock-photos]
verify_jwt = false

[functions.generate-slide-image]
verify_jwt = false

[functions.export-slides]
verify_jwt = false

[functions.heygen-video]
verify_jwt = false
