project_id = "reisbxeeozmvfdzruvui"

[functions.research-topic]
verify_jwt = false

[functions.generate-titles]
verify_jwt = false

[functions.generate-outline]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.generate-voice]
verify_jwt = false
